### ISSUE TITLE
Version on master is older than latest released version

### ISSUE THREAD

**Issue by jpsamaroo** [zgornel/ConceptnetNumberbatch.jl#12]
The General registry has versions of this package up to 0.1.5, but on master the package is at 0.1.2. This was breaking my attempts to dev this package locally, but manually switching the UUID to the one in General and messing with the Manifest fixed this. How could this have happened, and is it fixable?

**Comment by zgornel** [comment]
Hmm, I will have to look into this, strange. Will do as soon as possible and revert back. Thanks ;)

EDIT: Seems that `Project.toml` was not updated beyond `v0.1.2`.

**Comment by zgornel** [comment]
#13 Should hopefully fix this; somehow, the uuid has been changed, probably during the large General revamp from some time ago...
